### ISSUE TITLE
Database cartridge doesn't work?

### ISSUE THREAD

**Issue by AlecTaylor** [prelegalwonder/openshift_web2py#10]
I ran: `rhc app cartridge add -c postgresql-8.4 -a [appname]`

And replaced the sqlite line in my db.py with:

   `from os import environ as myenv
       DB_URL = myenv['postgresql://<ip_address>:5432/']+myenv['muts']
       db = DAL(DB_URL)`

But got a key error with the postgres line.

How do I get this to work?

As an aside, can I set it then when viewed on my local machine it uses sqlite, and when it's on openshift it uses postgres?

Thanks for all suggestions,

Alec Taylor

**Comment by prelegalwonder** [comment]
Use the example verbatim. myenv will grab the values of the environment variables inside the ' ' 

To switch between postgres and sqlite just put a conditional test for the openshift vars and if it fails, declare the sqlite config.

**Comment by prelegalwonder** [comment]
Verbatim with the exception you'll use   OPENSHIFT_DB_URL instead of OPENSHIFT_NOSQL_DB_URL since you're using postgres.

**Comment by srochy** [comment]
Hi,

Just wanted to mention a small issue I've noticed when using OpenShift's environment variables:OpenShift uses the postgresql:// prefix while web2py only understands the postrges:// prefix (Look here: http://web2py.com/books/default/chapter/29/06).

In my DB model, I use:

DB_URL = myenv['OPENSHIFT_DB_URL']+myenv['OPENSHIFT_APP_NAME']
DB_URL = DB_URL.replace("postgresql://", "postgres://")
db = DAL(DB_URL)

Saar

**Comment by prelegalwonder** [comment]
ahh ok thanks for the heads up! I'll ask Massimo if we can put some conditional checks in the DAL to handle the various addressing scheme if both are valid.

That looks like an easy enough work-around in the meantime. Thanks for the example / fix!
