### ISSUE TITLE
problem with module loading using instantpress

### ISSUE THREAD

**Issue by greaneym** [prelegalwonder/openshift_web2py#14]
Hello Andrew,

I am trying out the instantpress app from web2py and am getting a module load error.  Do you know how I can get past this error?

<type 'exceptions.ImportError'> No module named applications.blog2.modules.appsettings

I am using the stable version of web2py and instantpress 2.1.2.

I checked that the module is present and it is and there is an empty init file in the subdirectories.  
The openshift build file is making the links to the applications and the gluon directories, checked this also.

Can you give me any suggestions?  The app works locally on my mac, so it may be related to openshift/linux import problem possibly. I posted the question on web2py but didn't identify openshift as my server.

thank you,
Margaret

**Comment by prelegalwonder** [comment]
Hey Margaret, 

If the module isn't in the root wsgi/web2py dir or in libs/gluon, you'll need to modify /wsgi/application to add it to the sys.path. 

Something like:

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'web2py','some_subdir_where_module_exists'))

If that doesn't help, update the ticket with where the module is located in the project structure and I'll see if I can replicate it.

Cheers,
Andrew

**Comment by greaneym** [comment]
thanks Andrew,

I will give this a try later today.

margaret

**Comment by greaneym** [comment]
Hi Andrew,

I've edited out some of the error message below but kept most of the info.

Here I've updated the application file to append the path,
---partial content of file named application below---
#!/usr/bin/env python

import os
import sys

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['web2py_path'] = os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi
', 'web2py') 

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'web2py')
)
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'libs', 'gluon', 
'web2py/applications/blog3/modules'))
sys.path.append(os.path.join(virtenv, 'lib/python2.6/site-packages'))

WEB2PY_LOG = os.path.join(os.environ['OPENSHIFT_LOG_DIR'],'web2py.log')

-----end of application file---

then,
the InstantPress w2p file was uploaded into an app called "blog3" and is in
the applications directory on the openshift server.  I can see my other apps but with this one I get an error, see below. For some reason it is not loading the appsettings module from the modules directory.
This does work on my local laptop, a mac.  Maybe I am not adding it to the path correctly in the sys.path.append?

thanks for your help,
Margaret

---error message when app named "blog3" is accessed on openshift server----

web2py™   (2, 0, 2, datetime.datetime(2012, 8, 30, 8, 9, 29), 'stable')
Python  Python 2.6.6: /usr/bin/python
TRACEBACK
1.
2.
3.
4.
5.
6.
7.
8.
9.
Traceback (most recent call last):
  File "/var/lib/openshift//python-2.6/repo/libs/gluon/restricted.py", line 209, in restricted
    exec ccode in environment
  File "/var/lib/openshift/(removedpath/wsgi/web2py/applications/blog3/models/00main.py", line 18, in <module>
    from appsettings import app_settings
  File "/var/lib/openshift//python-2.6/repo/libs/gluon/custom_import.py", line 295, in **call**
    raise e
ImportError: No module named applications.blog3.modules.appsettings
ERROR SNAPSHOT  
<type 'exceptions.ImportError'>(No module named applications.blog3.modules.appsettings)

inspect attributes

Frames
File /var/lib/openshift//python-2.6/repo/libs/gluon/restricted.py in restricted at line 209 
code

arguments

variables

File /var/lib/openshift/(removedpath)/wsgi/web2py/applications/blog3/models/00main.py in <module> at line 18 
code

arguments

variables

File /var/lib/openshift//python-2.6/repo/libs/gluon/custom_import.py in **call** at line 295 
code

arguments

variables

Function argument list
(self=<gluon.custom_import._Web2pyImporter object>, name='appsettings', globals={'A': <class 'gluon.html.A'>, 'B': <class 'gluon.html.B'>, 'BEAUTIFY': <class 'gluon.html.BEAUTIFY'>, 'BODY': <class 'gluon.html.BODY'>, 'BR': <class 'gluon.html.BR'>, 'BUTTON': <class 'gluon.html.BUTTON'>, 'CAT': <class 'gluon.html.CAT'>, 'CENTER': <class 'gluon.html.CENTER'>, 'CLEANUP': <class 'gluon.validators.CLEANUP'>, 'CODE': <class 'gluon.html.CODE'>, ...}, locals={'A': <class 'gluon.html.A'>, 'B': <class 'gluon.html.B'>, 'BEAUTIFY': <class 'gluon.html.BEAUTIFY'>, 'BODY': <class 'gluon.html.BODY'>, 'BR': <class 'gluon.html.BR'>, 'BUTTON': <class 'gluon.html.BUTTON'>, 'CAT': <class 'gluon.html.CAT'>, 'CENTER': <class 'gluon.html.CENTER'>, 'CLEANUP': <class 'gluon.validators.CLEANUP'>, 'CODE': <class 'gluon.html.CODE'>, ...}, fromlist=('app_settings',), level=-1)

Code listing
                except ImportError, e:
                    try:
                        return super(_Web2pyImporter, self).__call__(name, globals, locals,
                                                    fromlist, level)
                    except ImportError, e1:
                        raise e

```
    return super(_Web2pyImporter, self).__call__(name, globals, locals,
                                                fromlist, level)

def __import__dot(self, prefix, name, globals, locals, fromlist,
```

Variables
e   ImportError('No module named applications.blog3.modules.appsettings',)
Context
locals

request

session

response

IN FILE: /VAR/LIB/OPENSHIFT/xxxx(removedpath)/WSGI/WEB2PY/APPLICATIONS/BLOG3/MODELS/00MAIN.PY

**Comment by greaneym** [comment]
Andrew,
I've updated the github ticket with more info.

Margaret

**Comment by prelegalwonder** [comment]
Margaret,

Remove the sys.path you added and try this:

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'web2py', 'applications', 'blog3', 'modules'))

**Comment by greaneym** [comment]
Andrew,

this works. Thank you very much.  Also, I tried the older version of
instant press, which also uses modules, and this
does not require any env changes to the os path for some reason. But I am
glad you made this newer version work and now I've learned a lot more about
web2py.  Thanks,

Margaret

**Comment by prelegalwonder** [comment]
Glad to hear it Margaret :) It was my pleasure.
