### ISSUE TITLE
upgraded to 2.3.2 and admin doesn't work

### ISSUE THREAD

**Issue by greaneym** [prelegalwonder/openshift_web2py#15]
Hi Andrew,

today I upgraded from 2.0.8 to 2.3.2 and everything worked fine except the admin access.
There is no parameters_8080.py in this version.  I tried doing a git push of an updated parameters_8080.py, then I made a link to the 8000.py file
ln -s parameters_8080.py parameters_8000.py 

but that did not work.  I also just tried a parameters_8000.py file in place with a encrypted password that I pushed after creating locally but this did not work either. I appreciate any help.  thanks,
Margaret

**Comment by prelegalwonder** [comment]
Margaret,

Add an additional symlink to parameters_80.py as I narrowed down that's the one web2py looks for in the openshift environment.

**Comment by greaneym** [comment]
Andrew,

that one already did have a symbolic link to parameters_8080.py. After the
install the sym links were already there.

Do you mean that all the params files should now be sym linked to
parameters_80.py and that one has the hashed passwd?
ln -s parameters_80.py parameter8080.py,  like this?

Margaret

**Comment by prelegalwonder** [comment]
Hm ok, no I meant what's already there. parameters_8080.py -> parameters_80.py

If you want to make things less complicated, you can get rid of all your parameters files and just have one parameters_80.py with the password in it. 

You can setup a logging.conf for more logging too. I can assist with that if you like.

**Comment by greaneym** [comment]
I tried putting on a new encrypted password file that I know works on my
local install and did a git push, and that didn't work. And now I am locked
out of admin (for too many tries). I hope that times out.

I created a logging.conf file and put entries in the default.py of the
admin app which I am trying to debug. The log files go into the directory
logs in  /very/long/openshift/path/web2py/logs.

I am trying to figure out how to turn on logging now.

margaret

**Comment by prelegalwonder** [comment]
I'm currently using the 2.3.2 branch for a project I'm working on so I know it works. For the logging, as long as you have a properly configured logging.conf in wsgi/web2py dir, I believe it should take effect. 

just to confirm after you added your symlinks you did a git add and git commit before your push? If so, I would also ssh into the gear to make sure everything looks the way it should in $OPENSHIFT_REPO_DIR.

**Comment by greaneym** [comment]
thanks Andrew. I will try another install of the same version with just the
welcome app and check the admin. If that works ok, then it was just
probably a network problem while the upgrade was done, something must not
have transferred possibly. The symlinks were there after the install
without any action on my part. I'll check the repo dir env.

**Comment by greaneym** [comment]
Andrew,

I tried again with a different password transfer and it worked this time.
 Thanks for your help.
margaret

**Comment by prelegalwonder** [comment]
Glad to hear its working :)
