### ISSUE TITLE
Invalid password for admin interface

### ISSUE THREAD

**Issue by Zocket** [prelegalwonder/openshift_web2py#18]
Currently I use the openshift_web2py as my upstream repo. And I face the same problem as several other people have experienced -- I'm not able to access the admin interface.
What I did was:
1. start a web2py instance on my windows machine with admin password. 
2. copy the parameter file which contains the password to my openshift web2py local directory, rename it so that it's used for port 443. 
3. commit and push to openshift.

I was able to access login page, but it always complain about "invalid password".
I also checked the code of web2py, and it turned out to use the validators.CRYPT class to generate the password using SHA512. Then I use the same method to generate the hashed password, it looks in the same format as the one auto-generated. It didn't work either. web2py.uuid is used in generating password, which could differ in different environments.
How can I set a valid password for my web2py application?

**Comment by prelegalwonder** [comment]
Hi Yelei,

Since the gears are proxied by a higher level web-tier provided by Red Hat, the port you need to configure the parameters file for is actually port 80. 

Try copying parameters_443.py to parameters_80.py and doing a git add, commit and push and let me know if that helps. 

Cheers,
Andrew

**Comment by Zocket** [comment]
Hi Andrew,

It's working now!
Thank you very much for the help!

Yelei
