### ISSUE TITLE
Administrative password not working

### ISSUE THREAD

**Issue by ghost** [prelegalwonder/openshift_web2py#2]
Despite having added my password hash to parameters_8080.py I still get

```
admin disabled because unable to access password file
```

when trying to access `admin/default/index`.

**Comment by prelegalwonder** [comment]
Can you check to see if the symlinks were maintained during your git clone from github and push to your openshift repo? These links would be:

parameters_8080.py -> parameters_80.py
parameters_8080.py -> parameters_443.py
options_std.py -> options.py

If not, create those and git add the links, repush and let me know if that helps.

**Comment by ghost** [comment]
That was it. Thank you.
