### ISSUE TITLE
Using with latest trunk?

### ISSUE THREAD

**Issue by AlecTaylor** [prelegalwonder/openshift_web2py#3]
How do I use this with latest trunk?

Once I had the web2py up and running on openshift I tried deleting the web2py folder and cloning the latest one off of hg, but ended up not being able to access admin.

(getting "Internal error"s before I'm even shown the "enter password" screen for accessing admin)

**Comment by prelegalwonder** [comment]
Alec, can you share the exception or error you get?

I get:

ATTENTION: Login requires a secure (HTTPS) connection or running on localhost.  
but no errors or exceptions. 

I'm looking into why the wsgi isn't detecting the connection as https.

**Comment by prelegalwonder** [comment]
It looks like trunk was changed to use {{if request.is_https or request.is_local:}} in the admin default index view. Previously it was just providing the form.  

I've dumped the request details when using https url and it shows  'wsgi_url_scheme': 'http' which is what wsgibase in gluon/main checks for to determine request.is_https.

Digging further to see if this is an openshift wsgi issue or my provided wsgi setup file or something else.

**Comment by prelegalwonder** [comment]
This appears to be an issue with mod_wsgi on the python-2.6 gears in openshift. 
I've opened up this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=843326 

But I also need to do additional research on the wsgi spec to see how it's supposed to handle forwarded headers.

In the meantime I'm trying to figure a quick hack to get around this issue. I'm looking into modifying the request.is_https in wsgibase to use HTTP_X_FORWARDED_PROTO or something like that.

**Comment by prelegalwonder** [comment]
A quick fix for this is to modify gluon/main.py wsgibase (around line 411)  from:

request.is_https = request.env.wsgi_url_scheme \
to
request.is_https = request.env.http_x_forwarded_proto \

Alec, let me know if this helps. I'm currently using trunk admin on openshift with this change.

**Comment by AlecTaylor** [comment]
Thanks, I'm now getting a different error: `admin disabled because unable to access password file`

(and yes, I have tried accessing with https and http, and have added the _parameters_80.py_ and _parameters_8080.py_ files, first automatically; with **web2py -p [port number] -a [password]**, then when I got that error, added them manually; by copying over my local version of those files)

**Comment by prelegalwonder** [comment]
how about the symlink from parameters_8080.py -> parameters_443.py ?

**Comment by AlecTaylor** [comment]
Okay, I tried creating a `parameters_443.py` file with two methods:
1. Copying `parameters_8080.py` to `parameters_443.py`
2. Running **web2py -p 443 -a [password]**

Both presented me with the _admin disabled because unable to access password file_ page, instead of admin.

**Comment by prelegalwonder** [comment]
have you ssh'd into you gear and cd to $OPENSHIFT_REPO_DIR/wsgi/web2py and confirm that the parameters file is there? Maybe git add is ignoring it?

**Comment by AlecTaylor** [comment]
It is definitely there.

I event tried recreating the app, then deleting my local clone directory and recloning it.

It definitely contains all 3 parameters files.

**Comment by prelegalwonder** [comment]
can you try copying the contents of wsgi/web2py/\* into the libs/ dir  minus applications dir and do a git add / commit etc and push that up and see if it works?

**Comment by AlecTaylor** [comment]
Okay, after doing many things manually on my end; I was presented with an "Internal error" page.

The admin did work fine on the other web2py version, when I followed its guide on your page. Maybe you can revise it, e.g.: put it onto another branch?

Because it most certainly isn't working on my end, and I have tried it multiple times following your recommendations to the letter.

**Comment by prelegalwonder** [comment]
https://github.com/prelegalwonder/openshift_web2py/tree/dev

**Comment by AlecTaylor** [comment]
Perfect, it's all working now.

Thanks :)

As an aside, please remove that branch. It seems you have left your ``parameters_*.py` files in-tact, hash and all.

**Comment by prelegalwonder** [comment]
Glad to hear it :)  It's fine it was just a test env with a random pass. I'll leave it in place for any others looking to use trunk =] Thanks for being the guinea pig and being so patient!

**Comment by prelegalwonder** [comment]
Just FYI, OpenShift has a pull request in to address this based off the above bugzilla. Shouldn't need the workaround soon.

https://github.com/openshift/crankcase/pull/311

**Comment by AlecTaylor** [comment]
Looks like it was merged soon after you commented above :)
