### ISSUE TITLE
Running web2py locally, for tests between OpenShift pushes?

### ISSUE THREAD

**Issue by AlecTaylor** [prelegalwonder/openshift_web2py#4]
Since I'm new to web2py, I'm often making mistakes, reading the ticket, then fixing said mistakes.

Usually they are just simple syntax errors.

Unfortunately OpenShift—unlike most other hosts—uses git rather than, for example: SFTP.

This means that I need to fill in a commit msg,  then wait ~30 seconds whilst it pushes; for after ever change I make. If there is a syntax error after all this, I facepalm >.<

Is there a way I can run with the web2py locally on my computer, i.e.: from the `wsgi\web2py`` directory?

My attempts left me without access to admin (see ticket: http://fiddle.jshell.net/AlecTaylor/wqYmA/show/light/)

If this isn't possible, would it be possible to symbolically link or reference in some other way, an identical (and linked) copy of my application with a web2py installation from somewhere else?

[I'm running Windows]

Thanks for all suggestions,

Alec Taylor

**Comment by prelegalwonder** [comment]
Alec,

I'm not sure why you're getting that error. For options, I can think of a few things depending on which way you want to go.

1.) Run trunk in openshift and use the admin in the cloud coupled with the newly added git support to save progress. This would require you creating a specific git project (perhaps on github.com) that is your application and importing it into Web2py via the "Upload and Install packed Application" dialog.

2.) Run a vanilla copy of trunk locally and use the openshift deployer dialog when you're ready to push changes up and you've tested your changes locally.

3.) I _think_ could symlink the application directory from a vanilla install into the openshift_template wsgi/web2py/applications/ dir so you'd just need to commit and push when ready. not sure if the symlink would cause any git weirdness. 

All of the built-in git support (OpenShift Deployer / Import, pull, push) should work equally as well on windows as long as you install the GitPython module.

Regards,
Andrew

**Comment by AlecTaylor** [comment]
No worries, just figured out how to use the NTFS 3.0+ feature of Directory Junctures, it should all work fine now.

:)
