### ISSUE TITLE
Version 2.0.3 out

### ISSUE THREAD

**Issue by AlecTaylor** [prelegalwonder/openshift_web2py#7]
Looks like Massimo made a mistake in 2.0.2 and released a new version a few hours later.

Could you please upgrade master?

Thanks

**Comment by prelegalwonder** [comment]
I'll probably wait a week or two to let the point-releases shake out as others find bugs etc. You can use the upgrade button in the admin page or upgrade manually by downloading 2.0.3 and copying it over the wsgi/web2py directory and moving wsgi/web2py/gluon to libs/gluon in the mean-time.

**Comment by AlecTaylor** [comment]
Version 2.0.8 has been released, did you want to upgrade to that or still wait a bit longer?

**Comment by prelegalwonder** [comment]
I'll update to 2.0.9.  Then 2.1 and 2.2

**Comment by AlecTaylor** [comment]
Great, thanks :)

**Comment by prelegalwonder** [comment]
2.0.9 is added. Give it a spin when you have a chance and let me know if you see anything that needs to be addressed.

**Comment by AlecTaylor** [comment]
Great, thanks =)
