### ISSUE TITLE
An issue with the web2py skeleton

### ISSUE THREAD

**Issue by srochy** [prelegalwonder/openshift_web2py#9]
Hi,

Thanks for creating this skeleton, it's been very helpful!

One thing I've noticed:
In .openshift/action_hooks/build rsync is not instructed to delete files that are missing from source. This causes deleted files to pile up at the destination.
I've fixed it in my repository by adding a --delete flag to rsync.

Thanks!
Saar

**Comment by prelegalwonder** [comment]
Yeah, I saw that. I'm not an rsync guru. I wasn't sure how to handle that the first time since no apps will exist in the data dir.

**Comment by prelegalwonder** [comment]
Nevermind, I'm thinking of a different problem where when you delete an app using the online ide, it doesn't get removed from the source. I'll experiment with delete and commit the changes. Thanks for the info!

**Comment by srochy** [comment]
Great, thanks!
